//
//  SubdivisionsUgandaLevel1.swift
//  
//
//  Created by Evan Anderson on 2/14/23.
//

import Foundation

public typealias SubdivisionsUgandaLevel1 = Locale.Region.Subdivision.Level1.Uganda

public extension Locale.Region.Subdivision.Level1 {
    @SubdivisionLevel1(region: Locale.Region.uganda, allSameType: false, type: Locale.Region.SubdivisionType.district)
    struct Uganda : Locale.Region.Subdivision.Level1Protocol {

        public var type : Locale.Region.SubdivisionType {
            switch self {
            case .kampala:
                return Locale.Region.SubdivisionType.city
            default:
                return Locale.Region.SubdivisionType.district
            }
        }
    }
}

@SubdivisionCases
public extension SubdivisionsUgandaLevel1 { // https://en.wikipedia.org/wiki/Districts_of_Uganda | https://en.wikipedia.org/wiki/ISO_3166-2:UG
    static let abim = get("314")
    static let adjumani = get("301")
    static let agago = get("322")
    static let alebtong = get("323")
    static let amolatar = get("315")
    static let amudat = get("324")
    static let amuria = get("216")
    static let amuru = get("316")
    static let apac = get("302")
    static let arua = get("303")
    static let budaka = get("217")
    static let bududa = get("218")
    static let bugiri = get("201")
    static let bugweri = get("235")
    static let buhweju = get("420")
    static let buikwe = get("117")
    static let bukedea = get("219")
    static let bukomansimbi = get("118")
    static let bukwo = get("220")
    static let bulambuli = get("225")
    static let buliisa = get("416")
    static let bundibugyo = get("401")
    static let bunyangabu = get("430")
    static let bushenyi = get("402")
    static let busia = get("202")
    static let butaleja = get("221")
    static let butambala = get("119")
    static let butebo = get("233")
    static let buvuma = get("120")
    static let buyende = get("226")
    static let dokolo = get("317")
    static let gomba = get("121")
    static let gulu = get("304")
    static let hoima = get("403")
    static let ibanda = get("417")
    static let iganga = get("203")
    static let isingiro = get("418")
    static let jinja = get("204")
    static let kaabong = get("318")
    static let kabale = get("404")
    static let kabarole = get("405")
    static let kaberamaido = get("213")
    static let kagadi = get("427")
    static let kakumiro = get("428")
    static let kalaki = get("237")
    static let kalangala = get("101")
    static let kaliro = get("222")
    static let kalungu = get("122")
    static let kamuli = get("205")
    static let kamwenge = get("413")
    static let kanungu = get("414")
    static let kapchorwa = get("206")
    static let kapelebyong = get("236")
    static let karenga = get("335")
    static let kasanda = get("126")
    static let kasese = get("406")
    static let katakwi = get("207")
    static let kayunga = get("112")
    static let kazo = get("433")
    static let kibaale = get("407")
    static let kiboga = get("103")
    static let kibuku = get("227")
    static let kikuube = get("432")
    static let kiruhura = get("419")
    static let kiryandongo = get("421")
    static let kisoro = get("408")
    static let kitagwenda = get("434")
    static let kitgum = get("305")
    static let koboko = get("319")
    static let kole = get("325")
    static let kotido = get("306")
    static let kumi = get("208")
    static let kwania = get("333")
    static let kween = get("228")
    static let kyankwanzi = get("123")
    static let kyegegwa = get("422")
    static let kyenjojo = get("415")
    static let kyotera = get("125")
    static let lamwo = get("326")
    static let lira = get("307")
    static let luuka = get("229")
    static let luweero = get("104")
    static let lwengo = get("124")
    static let lyantonde = get("114")
    static let madi_okollo = get("336")
    static let manafwa = get("223")
    static let maracha = get("320")
    static let masaka = get("105")
    static let masindi = get("409")
    static let mayuge = get("214")
    static let mbale = get("209")
    static let mbarara = get("410")
    static let mitooma = get("423")
    static let mityana = get("115")
    static let moroto = get("308")
    static let moyo = get("309")
    static let mpigi = get("106")
    static let mubende = get("107")
    static let mukono = get("108")
    static let nabilatuk = get("334")
    static let nakapiripirit = get("311")
    static let nakaseke = get("116")
    static let nakasongola = get("109")
    static let namayingo = get("230")
    static let namisindwa = get("234")
    static let namutumba = get("224")
    static let napak = get("327")
    static let nebbi = get("310")
    static let ngora = get("231")
    static let ntoroko = get("424")
    static let ntungamo = get("411")
    static let nwoya = get("328")
    static let obongi = get("337")
    static let omoro = get("331")
    static let otuke = get("329")
    static let oyam = get("321")
    static let pader = get("312")
    static let pakwach = get("332")
    static let pallisa = get("210")
    static let rakai = get("110")
    static let rubanda = get("429")
    static let rubirizi = get("425")
    static let rukiga = get("431")
    static let rukungiri = get("412")
    static let rwampara = get("435")
    static let sembabule = get("111")
    static let serere = get("232")
    static let sheema = get("426")
    static let sironko = get("215")
    static let soroti = get("211")
    static let terego = get("TER") // TODO: FIND
    static let tororo = get("212")
    static let wakiso = get("113")
    static let yumbe = get("313")
    static let zombo = get("330")

    static let kampala = get("102")
}
