//
//  CitiesUnitedStatesAlabama.swift
//  
//
//  Created by Evan Anderson on 9/23/22.
//

import Foundation

public enum CitiesUnitedStatesAlabama : String, SovereignStateCity { // https://en.wikipedia.org/wiki/List_of_municipalities_in_Alabama
    case abbeville
    case adamsville
    case addison
    case akron
    case alabaster
    case albertville
    case alexander_city
    case aliceville
    case allgood
    case altoona
    case andalusia
    case anderson
    case anniston
    case arab
    case ardmore
    case argo
    case ariton
    case arley
    case ashford
    case ashland
    case ashville
    case athens
    case atmore
    case attalla
    case auburn
    case autaugaville
    case avon
    
    case babbie
    case baileyton
    case bakerhill
    case banks
    case bay_minette
    case bayou_la_batre
    case bear_creek
    case beatrice
    case beaverton
    case belk
    case benton
    case berlin
    case berry
    case bessemer
    case billingsley
    case birmingham
    case black
    case blountsville
    case blue_springs
    case boaz
    case boligee
    case bon_air
    case brantley
    case brent
    case brewton
    case bridgeport
    case brighton
    case brilliant
    case brookside
    case brookwood
    case brundidge
    case butler
    
    case calera
    case camden
    case camp_hill
    case carbon_hill
    case cardiff
    case carolina
    case carrollton
    case castleberry
    case cedar_bluff
    case center_point
    case centre
    case centreville
    case chatom
    case chelsea
    case cherokee
    case chickasaw
    case childersburg
    case citronelle
    case clanton
    case clay
    case clayhatchee
    case clayton
    case cleveland
    case clio
    case coaling
    case coffee_springs
    case coffeeville
    case coker
    case collinsville
    case colony
    case columbia
    case columbiana
    case coosada
    case cordova
    case cottonwood
    case county_line
    case courtland
    case cowarts
    case creola
    case crossville
    case cuba
    case cullman
    case cusseta
    
    case dadeville
    case daleville
    case daphne
    case dauphin_island
    case daviston
    case dayton
    case deatsville
    case decatur
    case demopolis
    case detroit
    case dodge_city
    case dora
    case dothan
    case double_springs
    case douglas
    case dozier
    case dutton
    
    case east_brewton
    case eclectic
    case edwardsville
    case elba
    case elberta
    case eldridge
    case elkmont
    case elmore
    case emelle
    case enterprise
    case epes
    case ethelsville
    case eufaula
    case eutaw
    case eva
    case evergreen
    case excel
    
    case fairfield
    case fairhope
    case fairview
    case falkville
    case faunsdale
    case fayette
    case five_points
    case flomaton
    case florala
    case florence
    case foley
    case forkland
    case fort_deposit
    case fort_payne
    case franklin
    case frisco_city
    case fruithurst
    case fulton
    case fultondale
    case fyffe
    
    case gadsden
    case gainesville
    case gantt
    case garden_city
    case gardendale
    case gaylesville
    case geiger
    case geneva
    case georgiana
    case geraldine
    case gilbertown
    case glen_allen
    case glencoe
    case glenwood
    case goldville
    case good_hope
    case goodwater
    case gordo
    case gordon
    case gordonville
    case goshen
    case grant
    case graysville
    case greensboro
    case greenville
    case grimes
    case grove_hill
    case gu_win
    case guin
    case gulf_shores
    case guntersville
    case gurley
    
    case hackleburg
    case haleburg
    case haleyville
    case hamilton
    case hammondville
    case hanceville
    case harpersville
    case hartford
    case hartselle
    case hayden
    case hayneville
    case headland
    case heath
    case heflin
    case helena
    case henagar
    case highland_lake
    case hillsboro
    case hobson_city
    case hodges
    case hokes_bluff
    case holly_pond
    case hollywood
    case homewood
    case hoover
    case horn_hill
    case hueytown
    case huntsville
    case hurtsboro
    case hytop
    
    case ider
    case indian_springs_village
    case irondale
    
    case jackson
    case jacksons_gap
    case jacksonville
    case jasper
    case jemison
    
    case kansas
    case kellyton
    case kennedy
    case killen
    case kimberly
    case kinsey
    case kinston
    
    case lafayette
    case lake_view
    case lakeview
    case lanett
    case langston
    case leeds
    case leesburg
    case leighton
    case lester
    case level_plains
    case lexington
    case libertyville
    case lincoln
    case linden
    case lineville
    case lipscomb
    case lisman
    case littleville
    case livingston
    case loachapoka
    case lockhart
    case locust_fork
    case louisville
    case lowndesboro
    case loxley
    case luverne
    case lynn
    
    case madison
    case madrid
    case magnolia_springs
    case malvern
    case maplesville
    case margaret
    case marion
    case maytown
    case mcintosh
    case mckenzie
    case mcmullen
    case memphis
    case mentone
    case midfield
    case midland_city
    case midway
    case millbrook
    case millport
    case millry
    case mobile
    case monroeville
    case montevallo
    case montgomery
    case moody
    case mooresville
    case morris
    case mosses
    case moulton
    case moundville
    case mount_vernon
    case mountain_brook
    case mulga
    case munford
    case muscle_shoals
    case myrtlewood
    
    case napier_field
    case natural_bridge
    case nauvoo
    case nectar
    case needham
    case new_brockton
    case new_hope
    case new_site
    case newbern
    case newton
    case newville
    case north_courtland
    case north_johns
    case northport
    case notasulga
    
    case oak_grove
    case oak_hill
    case oakman
    case odenville
    case ohatchee
    case oneonta
    case onycha
    case opelika
    case opp
    case orange_beach
    case orrville
    case owens_cross_roads
    case oxford
    case ozark
    
    case paint_rock
    case parrish
    case pelham
    case pell_city
    case pennington
    case perdido_beach
    case petrey
    case phenix_city
    case phil_campbell
    case pickensville
    case piedmont
    case pike_road
    case pinckard
    case pine_apple
    case pine_hill
    case pine_ridge
    case pinson
    case pisgah
    case pleasant_grove
    case pleasant_groves
    case pollard
    case powell
    case prattville
    case priceville
    case prichard
    case providence
    
    case ragland
    case rainbow_city
    case rainsville
    case ranburne
    case red_bay
    case red_level
    case reece_city
    case reform
    case rehobeth
    case repton
    case ridgeville
    case river_falls
    case riverside
    case riverview
    case roanoke
    case robertsdale
    case rockford
    case rogersville
    case rosa
    case russellville
    case rutledge
    
    case samson
    case sand_rock
    case sanford
    case saraland
    case sardis_city
    case satsuma
    case scottsboro
    case section
    case selma
    case sheffield
    case shiloh
    case shorter
    case silas
    case silverhill
    case sipsey
    case skyline
    case slocomb
    case smiths_station
    case snead
    case somerville
    case south_vinemont
    case southside
    case spanish_fort
    case springville
    case st_florian
    case steele
    case stevenson
    case sulligent
    case sumiton
    case summerdale
    case susan_moore
    case sweet_water
    case sylacauga
    case sylvan_springs
    case sylvania
    
    case talladega
    case talladega_springs
    case tallassee
    case tarrant
    case taylor
    case thomaston
    case thomasville
    case thorsby
    case town_creek
    case toxey
    case trafford
    case triana
    case trinity
    case troy
    case trussville
    case tuscaloosa
    case tuscumbia
    case tuskegee
    case twin
    
    case union
    case union_grove
    case union_springs
    case uniontown
    
    case valley
    case valley_grande
    case valley_head
    case vance
    case vernon
    case vestavia_hills
    case vina
    case vincent
    case vredenburgh
    
    case wadley
    case waldo
    case walnut_grove
    case warrior
    case waterloo
    case waverly
    case weaver
    case webb
    case wedowee
    case west_blocton
    case west_jefferson
    case west_point
    case westover
    case wetumpka
    case white_hall
    case wilsonville
    case wilton
    case winfield
    case woodland
    case woodstock
    case woodville
    
    case yellow_bluff
    case york
    
    public var subdivision : any SovereignStateSubdivision {
        return SubdivisionsUnitedStates.alabama
    }
}
