//
//  CitiesUnitedStatesTexas.swift
//  
//
//  Created by Evan Anderson on 9/22/22.
//

import Foundation

public enum CitiesUnitedStatesTexas : String, SovereignStateCity { // https://en.wikipedia.org/wiki/List_of_municipalities_in_Texas
    case abbott
    case abernathy
    case abilene
    case ackerly
    case addison
    case adrian
    case agua_dulce
    case alamo
    case alamo_heights
    case alba
    case albany
    case aledo
    case alice
    case allen
    case alma
    case alpine
    case alto
    case alton
    case alvarado
    case alvin
    case alvord
    case amarillo
    case ames
    case amherst
    case anahuac
    case anderson
    case andrews
    case angleton
    case angus
    case anna
    case annetta
    case annetta_north
    case annetta_south
    case annona
    case anson
    case anthony
    case anton
    case appleby
    case aquilla
    case aransas_pass
    case archer_city
    case arcola
    case argyle
    case arlington
    case arp
    case asherton
    case aspermont
    case athens
    case atlanta
    case aubrey
    case aurora
    case austin
    case austwell
    case avery
    case avinger
    case azle
    
    case bailey
    case baileys_prairie
    case baird
    case balch_springs
    case balcones_heights
    case ballinger
    case balmorhea
    case bandera
    case bangs
    case bardwell
    case barry
    case barstow
    case bartlett
    case bartonville
    case bastrop
    case bay_city
    case bayou_vista
    case bayside
    case baytown
    case bayview
    case beach_city
    case bear_creek
    case beasley
    case beaumont
    case beckville
    case bedford
    case bedias
    case bee_cave
    case beeville
    case bellaire
    case bellevue
    case bellmead
    case bells
    case bellville
    case belton
    case benavides
    case benbrook
    case benjamin
    case berryville
    case bertram
    case beverly_hills
    case bevil_oaks
    case big_lake
    case big_sandy
    case big_spring
    case big_wells
    case bishop
    case bishop_hills
    case blackwell
    case blanco
    case blanket
    case bloomburg
    case blooming_grove
    case blossom
    case blue_mound
    case blue_ridge
    case blum
    case boerne
    case bogata
    case bonham
    case bonney
    case booker
    case borger
    case bovina
    case bowie
    case boyd
    case brackettville
    case brady
    case brazoria
    case brazos_country
    case breckenridge
    case bremond
    case brenham
    case briarcliff
    case briaroaks
    case bridge_city
    case bridgeport
    case broaddus
    case bronte
    case brookshire
    case brookside_village
    case browndell
    case brownfield
    case brownsboro
    case brownsville
    case brownwood
    case bruceville_eddy
    case bryan
    case bryson
    case buckholts
    case buda
    case buffalo
    case buffalo_gap
    case buffalo_springs
    case bullard
    case bulverde
    case bunker_hill_village
    case burkburnett
    case burke
    case burleson
    case burnet
    case burton
    case byers
    case bynum
    
    case cactus
    case caddo_mills
    case caldwell
    case callisburg
    case calvert
    case cameron
    case camp_wood
    case campbell
    case canadian
    case caney_city
    case canton
    case canyon
    case carbon
    case carls_corner
    case carmine
    case carrizo_springs
    case carrollton
    case carthage
    case cashion_community
    case castle_hills
    case castroville
    case cedar_hill
    case cedar_park
    case celeste
    case celina
    case center
    case centerville
    case chandler
    case channing
    case charlotte
    case chester
    case chico
    case childress
    case chillicothe
    case china
    case china_grove
    case chireno
    case christine
    case cibolo
    case cisco
    case clarendon
    case clarksville
    case clarksville_city
    case claude
    case clear_lake_shores
    case cleburne
    case cleveland
    case clifton
    case clint
    case clute
    case clyde
    case coahoma
    case cockrell_hill
    case coffee_city
    case coldspring
    case coleman
    case college_station
    case colleyville
    case collinsville
    case colmesneil
    case colorado_city
    case columbus
    case comanche
    case combes
    case combine
    case commerce
    case como
    case conroe
    case converse
    case cool
    case coolidge
    case cooper
    case coppell
    case copper_canyon
    case copperas_cove
    case corinth
    case corpus_christi
    case corrigan
    case corsicana
    case cottonwood
    case cottonwood_shores
    case cotulla
    case coupland
    case cove
    case covington
    case coyote_flats
    case crandall
    case crane
    case cranfills_gap
    case crawford
    case creedmoor
    case cresson
    case crockett
    case crosbyton
    case cross_plains
    case cross_roads
    case cross_timber
    case crowell
    case crowley
    case crystal_city
    case cuero
    case cumby
    case cuney
    case cushing
    case cut_and_shoot
    
    case daingerfield
    case daisetta
    case dalhart
    case dallas
    case dalworthington_gardens
    case danbury
    case darrouzett
    case dawson
    case dayton
    case dayton_lakes
    case de_kalb
    case de_leon
    case dean
    case decatur
    case decordova
    case deer_park
    case del_rio
    case dell_city
    case denison
    case denton
    case denver_city
    case deport
    case desoto
    case detroit
    case devers
    case devine
    case diboll
    case dickens
    case dickinson
    case dilley
    case dimmitt
    case dish
    case dodd_city
    case dodson
    case domino
    case donna
    case dorchester
    case double_oak
    case douglassville
    case draper
    case dripping_springs
    case driscoll
    case dublin
    case dumas
    case duncanville
    
    case eagle_lake
    case eagle_pass
    case early
    case earth
    case east_bernard
    case east_mountain
    case east_tawakoni
    case eastland
    case easton
    case ector
    case edcouch
    case eden
    case edgecliff_village
    case edgewood
    case edinburg
    case edmonson
    case edna
    case edom
    case el_campo
    case el_cenizo
    case el_lago
    case el_paso
    case eldorado
    case electra
    case elgin
    case elkhart
    case ellinger
    case elmendorf
    case elsa
    case emhouse
    case emory
    case enchanted_oaks
    case encinal
    case ennis
    case escobares
    case estelline
    case euless
    case eureka
    case eustace
    case evant
    case everman
    
    case fair_oaks_ranch
    case fairchilds
    case fairfield
    case fairview
    case falfurrias
    case falls_city
    case farmers_branch
    case farmersville
    case farwell
    case fate
    case fayetteville
    case ferris
    case flatonia
    case florence
    case floresville
    case flower_mound
    case floydada
    case follett
    case forest_hill
    case forney
    case forsan
    case fort_stockton
    case fort_worth
    case franklin
    case frankston
    case fredericksburg
    case freeport
    case freer
    case friendswood
    case friona
    case frisco
    case fritch
    case frost
    case fruitvale
    case fulshear
    case fulton
    
    case gainesville
    case galena_park
    case gallatin
    case galveston
    case ganado
    case garden_ridge
    case garland
    case garrett
    case garrison
    case gary_city
    case gatesville
    case george_west
    case georgetown
    case gholson
    case giddings
    case gilmer
    case gladewater
    case glen_rose
    case glenn_heights
    case godley
    case goldsmith
    case goldthwaite
    case goliad
    case golinda
    case gonzales
    case goodlow
    case goodrich
    case gordon
    case goree
    case gorman
    case graford
    case graham
    case granbury
    case grand_prairie
    case grand_saline
    case grandfalls
    case grandview
    case granger
    case granite_shoals
    case granjeno
    case grapeland
    case grapevine
    case grays_prairie
    case greenville
    case gregory
    case grey_forest
    case groesbeck
    case groom
    case groves
    case groveton
    case gruver
    case gun_barrel_city
    case gunter
    case gustine
    
    case hackberry
    case hale_center
    case hallettsville
    case hallsburg
    case hallsville
    case haltom_city
    case hamilton
    case hamlin
    case happy
    case hardin
    case harker_heights
    case harlingen
    case hart
    case haskell
    case haslet
    case hawk_cove
    case hawkins
    case hawley
    case hays
    case hearne
    case heath
    case hebron
    case hedley
    case hedwig_village
    case helotes
    case hemphill
    case hempstead
    case henderson
    case henrietta
    case hereford
    case hewitt
    case hickory_creek
    case hico
    case hidalgo
    case hideaway
    case higgins
    case highland_haven
    case highland_park
    case highland_village
    case hill_country_village
    case hillcrest
    case hillsboro
    case hilshire_village
    case hitchcock
    case holiday_lakes
    case holland
    case holliday
    case hollywood_park
    case hondo
    case honey_grove
    case hooks
    case horizon_city
    case horseshoe_bay
    case houston
    case howardwick
    case howe
    case hubbard
    case hudson
    case hudson_oaks
    case hughes_springs
    case humble
    case hunters_creek_village
    case huntington
    case huntsville
    case hurst
    case hutchins
    case hutto
    case huxley
    
    case idalou
    case impact
    case indian_lake
    case industry
    case ingleside
    case ingleside_on_the_bay
    case ingram
    case iola
    case iowa_colony
    case iowa_park
    case iraan
    case iredell
    case irving
    case italy
    case itasca
    case ivanhoe
    
    case jacinto_city
    case jacksboro
    case jacksonville
    case jamaica_beach
    case jarrell
    case jasper
    case jayton
    case jefferson
    case jersey_village
    case jewett
    case joaquin
    case johnson_city
    case jolly
    case jones_creek
    case jonestown
    case josephine
    case joshua
    case jourdanton
    case junction
    case justin
    
    case karnes_city
    case katy
    case kaufman
    case keene
    case keller
    case kemah
    case kemp
    case kempner
    case kendleton
    case kenedy
    case kenefick
    case kennard
    case kennedale
    case kerens
    case kermit
    case kerrville
    case kilgore
    case killeen
    case kingsbury
    case kingsville
    case kirby
    case kirbyville
    case kirvin
    case knollwood
    case knox_city
    case kosse
    case kountze
    case kress
    case krugerville
    case krum
    case kurten
    case kyle
    
    case la_feria
    case la_grange
    case la_grulla
    case la_joya
    case la_marque
    case la_porte
    case la_vernia
    case la_villa
    case la_ward
    case lacoste
    case lacy_lakeview
    case ladonia
    case lago_vista
    case laguna_vista
    case lake_bridgeport
    case lake_city
    case lake_dallas
    case lake_jackson
    case lake_tanglewood
    case lake_worth
    case lakeport
    case lakeside_san_patricio
    case lakeside_tarrant
    case lakeside_city
    case lakeview
    case lakeway
    case lakewood_village
    case lamesa
    case lampasas
    case lancaster
    case laredo
    case latexo
    case lavon
    case lawn
    case league_city
    case leakey
    case leander
    case leary
    case lefors
    case leon_valley
    case leona
    case leonard
    case leroy
    case levelland
    case lewisville
    case lexington
    case liberty
    case liberty_hill
    case lincoln_park
    case lindale
    case linden
    case lindsay
    case lipan
    case little_elm
    case little_river_academy
    case littlefield
    case live_oak
    case liverpool
    case livingston
    case llano
    case lockhart
    case lockney
    case log_cabin
    case lometa
    case lone_oak
    case lone_star
    case longview
    case loraine
    case lorena
    case lorenzo
    case los_fresnos
    case los_indios
    case los_ybanez
    case lott
    case lovelady
    case lowry_crossing
    case lubbock
    case lucas
    case lueders
    case lufkin
    case luling
    case lumberton
    case lyford
    case lytle
    
    case mabank
    case madisonville
    case magnolia
    case malakoff
    case malone
    case manor
    case mansfield
    case manvel
    case marble_falls
    case marfa
    case marietta
    case marion
    case marlin
    case marquez
    case marshall
    case mart
    case martindale
    case mason
    case matador
    case mathis
    case maud
    case maypearl
    case mcallen
    case mccamey
    case mcgregor
    case mckinney
    case mclean
    case mclendon_chisholm
    case meadow
    case meadowlakes
    case meadows_place
    case megargel
    case melissa
    case melvin
    case memphis
    case menard
    case mercedes
    case meridian
    case merkel
    case mertens
    case mertzon
    case mesquite
    case mexia
    case miami
    case midland
    case midlothian
    case midway
    case milano
    case mildred
    case miles
    case milford
    case millers_cove
    case millican
    case millsap
    case mineola
    case mineral_wells
    case mingus
    case mission
    case missouri_city
    case mobeetie
    case mobile_city
    case monahans
    case mont_belvieu
    case montgomery
    case moody
    case moore_station
    case moran
    case morgan
    case morgans_point
    case morgans_point_resort
    case morton
    case moulton
    case mount_calm
    case mount_enterprise
    case mount_pleasant
    case mount_vernon
    case mountain_city
    case muenster
    case muleshoe
    case mullin
    case munday
    case murchison
    case murphy
    case mustang
    case mustang_ridge
    
    case nacogdoches
    case naples
    case nash
    case nassau_bay
    case natalia
    case navarro
    case navasota
    case nazareth
    case nederland
    case needville
    case nevada
    case new_berlin
    case new_boston
    case new_braunfels
    case new_chapel_hill
    case new_deal
    case new_fairview
    case new_home
    case new_hope
    case new_london
    case new_summerfield
    case new_waverly
    case newark
    case newcastle
    case newton
    case neylandville
    case niederwald
    case nixon
    case nocona
    case nolanville
    case nome
    case noonday
    case nordheim
    case normangee
    case north_cleveland
    case north_richland_hills
    case northlake
    case novice
    
    case obrien
    case odonnell
    case oak_grove
    case oak_leaf
    case oak_point
    case oak_ridge_cooke
    case oak_ridge_kaufman
    case oak_ridge_north
    case oak_valley
    case oakwood
    case odem
    case odessa
    case oglesby
    case old_river_winfree
    case olmos_park
    case olney
    case olton
    case omaha
    case onalaska
    case opdyke_west
    case orange
    case orange_grove
    case orchard
    case ore_city
    case overton
    case ovilla
    case oyster_creek
    
    case paducah
    case paint_rock
    case palacios
    case palestine
    case palisades
    case palm_valley
    case palmer
    case palmhurst
    case palmview
    case pampa
    case panhandle
    case panorama_village
    case pantego
    case paradise
    case paris
    case parker
    case pasadena
    case pattison
    case patton_village
    case payne_springs
    case pearland
    case pearsall
    case pecan_gap
    case pecan_hill
    case pecos
    case pelican_bay
    case penelope
    case perryton
    case petersburg
    case petrolia
    case petronila
    case peñitas
    case pflugerville
    case pharr
    case pilot_point
    case pine_forest
    case pine_island
    case pinehurst
    case pineland
    case piney_point_village
    case pittsburg
    case plains
    case plainview
    case plano
    case plantersville
    case pleak
    case pleasant_valley
    case pleasanton
    case plum_grove
    case point
    case point_blank
    case point_comfort
    case point_venture
    case ponder
    case port_aransas
    case port_arthur
    case port_isabel
    case port_lavaca
    case port_neches
    case portland
    case post
    case post_oak_bend_city
    case poteet
    case poth
    case pottsboro
    case powell
    case poynor
    case prairie_view
    case premont
    case presidio
    case primera
    case princeton
    case progreso
    case progreso_lakes
    case prosper
    case providence_village
    case putnam
    case pyote
    
    case quanah
    case queen_city
    case quinlan
    case quintana
    case quitaque
    case quitman
    
    case ralls
    case rancho_viejo
    case ranger
    case rankin
    case ransom_canyon
    case ravenna
    case raymondville
    case red_lick
    case red_oak
    case redwater
    case refugio
    case reklaw
    case reno_lamar
    case reno_parker
    case retreat
    case rhome
    case rice
    case richardson
    case richland
    case richland_hills
    case richland_springs
    case richmond
    case richwood
    case riesel
    case rio_bravo
    case rio_grande_city
    case rio_hondo
    case rio_vista
    case rising_star
    case river_oaks
    case riverside
    case roanoke
    case roaring_springs
    case robert_lee
    case robinson
    case robstown
    case roby
    case rochester
    case rockdale
    case rockport
    case rocksprings
    case rockwall
    case rocky_mound
    case rogers
    case rollingwood
    case roma
    case roman_forest
    case ropesville
    case roscoe
    case rose_city
    case rose_hill_acres
    case rosebud
    case rosenberg
    case ross
    case rosser
    case rotan
    case round_mountain
    case round_rock
    case round_top
    case rowlett
    case roxton
    case royse_city
    case rule
    case runaway_bay
    case runge
    case rusk
    
    case sabinal
    case sachse
    case sadler
    case saginaw
    case salado
    case san_angelo
    case san_antonio
    case san_augustine
    case san_benito
    case san_diego
    case san_elizario
    case san_felipe
    case san_juan
    case san_leanna
    case san_marcos
    case san_patricio
    case san_perlita
    case san_saba
    case sanctuary
    case sandy_oaks
    case sandy_point
    case sanford
    case sanger
    case sansom_park
    case santa_anna
    case santa_clara
    case santa_fe
    case santa_rosa
    case savoy
    case schertz
    case schulenburg
    case scotland
    case scottsville
    case scurry
    case seabrook
    case seadrift
    case seagoville
    case seagraves
    case sealy
    case seguin
    case selma
    case seminole
    case seven_oaks
    case seven_points
    case seymour
    case shady_shores
    case shallowater
    case shamrock
    case shavano_park
    case shenandoah
    case shepherd
    case sherman
    case shiner
    case shoreacres
    case silsbee
    case silverton
    case simonton
    case sinton
    case skellytown
    case slaton
    case smiley
    case smithville
    case smyer
    case snook
    case snyder
    case socorro
    case somerset
    case somerville
    case sonora
    case sour_lake
    case south_houston
    case south_mountain
    case south_padre_island
    case southlake
    case southmayd
    case southside_place
    case spearman
    case splendora
    case spofford
    case spring_branch
    case spring_valley_village
    case springlake
    case springtown
    case spur
    case st_hedwig
    case st_jo
    case st_paul
    case stafford
    case stagecoach
    case stamford
    case stanton
    case staples
    case star_harbor
    case stephenville
    case sterling_city
    case stinnett
    case stockdale
    case stockton_bend
    case stratford
    case strawn
    case streetman
    case sudan
    case sugar_land
    case sullivan_city
    case sulphur_springs
    case sun_valley
    case sundown
    case sunnyvale
    case sunray
    case sunrise_beach_village
    case sunset_valley
    case surfside_beach
    case sweeny
    case sweetwater
    
    case taft
    case tahoka
    case talco
    case talty
    case tatum
    case taylor
    case taylor_lake_village
    case taylor_landing
    case teague
    case tehuacana
    case temple
    case tenaha
    case terrell
    case terrell_hills
    case texarkana
    case texas_city
    case texhoma
    case texline
    case the_colony
    case the_hills
    case thompsons
    case thorndale
    case thornton
    case thorntonville
    case thrall
    case three_rivers
    case throckmorton
    case tiki_island
    case timbercreek_canyon
    case timpson
    case tioga
    case tira
    case toco
    case todd_mission
    case tolar
    case tom_bean
    case tomball
    case tool
    case toyah
    case trent
    case trenton
    case trinidad
    case trinity
    case trophy_club
    case troup
    case troy
    case tulia
    case turkey
    case tuscola
    case tye
    case tyler
    
    case uhland
    case uncertain
    case union_grove
    case union_valley
    case universal_city
    case university_park
    case uvalde
    
    case valentine
    case valley_mills
    case valley_view
    case van
    case van_alstyne
    case van_horn
    case vega
    case venus
    case vernon
    case victoria
    case vidor
    case vinton
    case volente
    case von_ormy
    
    case waco
    case waelder
    case wake_village
    case waller
    case wallis
    case walnut_springs
    case warren_city
    case waskom
    case watauga
    case waxahachie
    case weatherford
    case webberville
    case webster
    case weimar
    case weinert
    case weir
    case wellington
    case wellman
    case wells
    case weslaco
    case west
    case west_columbia
    case west_lake_hills
    case west_orange
    case west_tawakoni
    case west_university_place
    case westbrook
    case westlake
    case weston
    case weston_lakes
    case westover_hills
    case westworth_village
    case wharton
    case wheeler
    case white_deer
    case white_oak
    case white_settlement
    case whiteface
    case whitehouse
    case whitesboro
    case whitewright
    case whitney
    case wichita_falls
    case wickett
    case willis
    case willow_park
    case wills_point
    case wilmer
    case wilson
    case wimberley
    case windcrest
    case windom
    case windthorst
    case winfield
    case wink
    case winnsboro
    case winona
    case winters
    case wixon_valley
    case wolfe_city
    case wolfforth
    case woodbranch
    case woodcreek
    case woodloch
    case woodsboro
    case woodson
    case woodville
    case woodway
    case wortham
    case wylie
    
    case yantis
    case yoakum
    case yorktown
    
    case zavalla
    
    public var subdivision : any SovereignStateSubdivision {
        return SubdivisionsUnitedStates.texas
    }
    
    public var real_name : String? {
        switch self {
        case .baileys_prairie: return "Bailey's Prairie"
        case .bruceville_eddy: return "Bruceville-Eddy"
        case .carls_corner: return "Carl's Corner"
        case .lacy_lakeview: return "Lacy-Lakeview"
        case .lakeside_san_patricio, .lakeside_tarrant:
            return "Lakeside"
        case .little_river_academy: return "Little River-Academy"
        case .mcallen: return "McAllen"
        case .mccamey: return "McCamey"
        case .mcgregor: return "McGregor"
        case .mckinney: return "McKinny"
        case .mclean: return "McLean"
        case .mclendon_chisholm: return "McLendon-Chisholm"
        case .millers_cove: return "Miller's Cove"
        case .morgans_point: return "Morgan's Point"
        case .morgans_point_resort: return "Morgan's Point Resort"
        case .obrien: return "O'Brien"
        case .odonnell: return "O'Donnell"
        case .oak_ridge_cooke, .oak_ridge_kaufman:
            return "Oak Ridge"
        case .old_river_winfree: return "Old River-Winfree"
        case .reno_lamar, .reno_parker:
            return "Reno"
        default: return nil
        }
    }
}
