//
//  CitiesUnitedStatesMinnesota.swift
//
//
//  Created by Evan Anderson on 7/19/22.
//

import Foundation

public enum CitiesUnitedStatesMinnesota : String, SovereignStateCity { // https://en.wikipedia.org/wiki/List_of_cities_in_Minnesota
    case ada
    case adams
    case adrian
    case afton
    case aitkin
    case akeley
    case albany
    case albert_lea
    case alberta
    case albertville
    case alden
    case aldrich
    case alexandria
    case alpha
    case altura
    case alvarado
    case amboy
    case andover
    case annandale
    case anoka
    case apple_valley
    case appleton
    case arco
    case arden_hills
    case argyle
    case arlington
    case ashby
    case askov
    case atwater
    case audubon
    case aurora
    case austin
    case avoca
    case avon
    
    case babbitt
    case backus
    case badger
    case bagley
    case balaton
    case barnesville
    case barnum
    case barrett
    case barry
    case battle_lake
    case baudette
    case baxter
    case bayport
    case beardsley
    case beaver_bay
    case beaver_creek
    case becker
    case bejou
    case belgrade
    case belle_plaine
    case bellechester
    case bellingham
    case beltrami
    case belview
    case bemidji
    case bena
    case benson
    case bertha
    case bethel
    case big_falls
    case big_lake
    case bigelow
    case bigfork
    case bingham_lake
    case birchwood_village
    case bird_island
    case biscay
    case biwabik
    case blackduck
    case blaine
    case blomkest
    case blooming_prairie
    case bloomington
    case blue_earth
    case bluffton
    case bock
    case borup
    case bovey
    case bowlus
    case boy_river
    case boyd
    case braham
    case brainerd
    case brandon
    case breckenridge
    case breezy_point
    case brewster
    case bricelyn
    case brook_park
    case brooklyn_center
    case brooklyn_park
    case brooks
    case brookston
    case brooten
    case browerville
    case browns_valley
    case brownsdale
    case brownsville
    case brownton
    case bruno
    case buckman
    case buffalo
    case buffalo_lake
    case buhl
    case burnsville
    case burtrum
    case butterfield
    case byron
    
    case caledonia
    case callaway
    case calumet
    case cambridge
    case campbell
    case canby
    case cannon_falls
    case canton
    case carlos
    case carlton
    case carver
    case cass_lake
    case cedar_mills
    case center_city
    case centerville
    case ceylon
    case champlin
    case chandler
    case chanhassen
    case chaska
    case chatfield
    case chickamaw_beach
    case chisago_city
    case chisholm
    case chokio
    case circle_pines
    case clara_city
    case claremont
    case clarissa
    case clarkfield
    case clarks_grove
    case clear_lake
    case clearbrook
    case clearwater
    case clements
    case cleveland
    case climax
    case clinton
    case clitherall
    case clontarf
    case cloquet
    case coates
    case cobden
    case cohasset
    case cokato
    case cold_spring
    case coleraine
    case cologne
    case columbia_heights
    case columbus
    case comfrey
    case comstock
    case conger
    case cook
    case coon_rapids
    case corcoran
    case correll
    case cosmos
    case cottage_grove
    case cottonwood
    case courtland
    case cromwell
    case crookston
    case crosby
    case crosslake
    case crystal
    case currie
    case cuyuna
    case cyrus
    
    case dakota
    case dalton
    case danube
    case danvers
    case darfur
    case darwin
    case dassel
    case dawson
    case dayton
    case de_graff
    case deephaven
    case deer_creek
    case deer_river
    case deerwood
    case delano
    case delavan
    case delhi
    case dellwood
    case denham
    case dennison
    case dent
    case detroit_lakes
    case dexter
    case dilworth
    case dodge_center
    case donaldson
    case donnelly
    case doran
    case dover
    case dovray
    case duluth
    case dumont
    case dundas
    case dundee
    case dunnell
    
    case eagan
    case eagle_bend
    case eagle_lake
    case east_bethel
    case east_grand_forks
    case east_gull_lake
    case easton
    case echo
    case eden_prairie
    case eden_valley
    case edgerton
    case edina
    case effie
    case eitzen
    case elba
    case elbow_lake
    case elgin
    case elizabeth
    case elk_river
    case elko_new_market
    case elkton
    case ellendale
    case ellsworth
    case elmdale
    case elmore
    case elrosa
    case ely
    case elysian
    case emily
    case emmons
    case erhard
    case erskine
    case evan
    case evansville
    case eveleth
    case excelsior
    case eyota
    
    case fairfax
    case fairmont
    case falcon_heights
    case faribault
    case farmington
    case farwell
    case federal_dam
    case felton
    case fergus_falls
    case fertile
    case fifty_lakes
    case finlayson
    case fisher
    case flensburg
    case floodwood
    case florence
    case foley
    case forada
    case forest_lake
    case foreston
    case fort_ripley
    case fosston
    case fountain
    case foxhome
    case franklin
    case frazee
    case freeborn
    case freeport
    case fridley
    case frost
    case fulda
    case funkley
    
    case garfield
    case garrison
    case garvin
    case gary
    case gaylord
    case gem_lake
    case geneva
    case genola
    case georgetown
    case ghent
    case gibbon
    case gilbert
    case gilman
    case glencoe
    case glenville
    case glenwood
    case glyndon
    case golden_valley
    case gonvick
    case good_thunder
    case goodhue
    case goodridge
    case goodview
    case graceville
    case granada
    case grand_marais
    case grand_meadow
    case grand_rapids
    case granite_falls
    case grant
    case grasston
    case green_isle
    case greenbush
    case greenfield
    case greenwald
    case greenwood
    case grey_eagle
    case grove_city
    case grygla
    case gully
    
    case hackensack
    case hadley
    case hallock
    case halma
    case halstad
    case ham_lake
    case hamburg
    case hammond
    case hampton
    case hancock
    case hanley_falls
    case hanover
    case hanska
    case harding
    case hardwick
    case harmony
    case harris
    case hartland
    case hastings
    case hatfield
    case hawley
    case hayfield
    case hayward
    case hazel_run
    case hector
    case heidelberg
    case henderson
    case hendricks
    case hendrum
    case henning
    case henriette
    case herman
    case hermantown
    case heron_lake
    case hewitt
    case hibbing
    case hill_city
    case hillman
    case hills
    case hilltop
    case hinckley
    case hitterdal
    case hoffman
    case hokah
    case holdingford
    case holland
    case hollandale
    case holloway
    case holt
    case hopkins
    case houston
    case howard_lake
    case hoyt_lakes
    case hugo
    case humboldt
    case hutchinson
    
    case ihlen
    case independence
    case international_falls
    case inver_grove_heights
    case iona
    case iron_junction
    case ironton
    case isanti
    case isle
    case ivanhoe
    
    case jackson
    case janesville
    case jasper
    case jeffers
    case jenkins
    case johnson
    case jordan
    
    case kandiyohi
    case karlstad
    case kasota
    case kasson
    case keewatin
    case kelliher
    case kellogg
    case kennedy
    case kenneth
    case kensington
    case kent
    case kenyon
    case kerkhoven
    case kerrick
    case kettle_river
    case kiester
    case kilkenny
    case kimball
    case kinbrae
    case kingston
    case kinney
    
    case la_crescent
    case la_prairie
    case la_salle
    case lafayette
    case lake_benton
    case lake_bronson
    case lake_city
    case lake_crystal
    case lake_elmo
    case lake_henry
    case lake_lillian
    case lake_park
    case lake_shore
    case lake_st_croix_beach
    case lake_wilson
    case lakefield
    case lakeland
    case lakeland_shores
    case lakeville
    case lamberton
    case lancaster
    case landfall
    case lanesboro
    case laporte
    case lastrup
    case lauderdale
    case le_center
    case le_roy
    case le_sueur
    case lengby
    case leonard
    case leonidas
    case lester_prairie
    case lewiston
    case lewisville
    case lexington
    case lilydale
    case lindstrom
    case lino_lakes
    case lismore
    case litchfield
    case little_canada
    case little_falls
    case littlefork
    case long_beach
    case long_lake
    case long_prairie
    case longville
    case lonsdale
    case loretto
    case louisburg
    case lowry
    case lucan
    case luverne
    case lyle
    case lynd
    
    case mabel
    case madelia
    case madison
    case madison_lake
    case magnolia
    case mahnomen
    case mahtomedi
    case manchester
    case manhattan_beach
    case mankato
    case mantorville
    case maple_grove
    case maple_lake
    case maple_plain
    case mapleton
    case mapleview
    case maplewood
    case marble
    case marietta
    case marine_on_st_croix
    case marshall
    case mayer
    case maynard
    case mazeppa
    case mcgrath
    case mcgregor
    case mcintosh
    case mckinley
    case meadowlands
    case medford
    case medicine_lake
    case medina
    case meire_grove
    case melrose
    case menahga
    case mendota
    case mendota_heights
    case mentor
    case middle_river
    case miesville
    case milaca
    case milan
    case millerville
    case millville
    case milroy
    case miltona
    case minneapolis
    case minneiska
    case minneota
    case minnesota_city
    case minnesota_lake
    case minnetonka
    case minnetonka_beach
    case minnetrista
    case mizpah
    case montevideo
    case montgomery
    case monticello
    case montrose
    case moorhead
    case moose_lake
    case mora
    case morgan
    case morris
    case morristown
    case morton
    case motley
    case mound
    case mounds_view
    case mountain_iron
    case mountain_lake
    case murdock
    case myrtle
    
    case nashua
    case nashwauk
    case nassau
    case nelson
    case nerstrand
    case nevis
    case new_auburn
    case new_brighton
    case new_germany
    case new_hope
    case new_london
    case new_munich
    case new_prague
    case new_richland
    case new_trier
    case new_ulm
    case new_york_mills
    case newfolden
    case newport
    case nicollet
    case nielsville
    case nimrod
    case nisswa
    case norcross
    case north_branch
    case north_mankato
    case north_oaks
    case north_st_paul
    case northfield
    case northome
    case northrop
    case norwood_young_america
    case nowthen
    
    case oak_grove
    case oak_park_heights
    case oakdale
    case odessa
    case odin
    case ogema
    case ogilvie
    case okabena
    case oklee
    case olivia
    case onamia
    case ormsby
    case orono
    case oronoco
    case orr
    case ortonville
    case osakis
    case oslo
    case osseo
    case ostrander
    case otsego
    case ottertail
    case owatonna
    
    case palisade
    case park_rapids
    case parkers_prairie
    case paynesville
    case pease
    case pelican_rapids
    case pemberton
    case pennock
    case pequot_lakes
    case perham
    case perley
    case peterson
    case pierz
    case pillager
    case pine_city
    case pine_island
    case pine_river
    case pine_springs
    case pipestone
    case plainview
    case plato
    case plummer
    case plymouth
    case porter
    case preston
    case princeton
    case prinsburg
    case prior_lake
    case proctor
    
    case quamba
    
    case racine
    case ramsey
    case randall
    case randolph
    case ranier
    case raymond
    case red_lake_falls
    case red_wing
    case redwood_falls
    case regal
    case remer
    case renville
    case revere
    case rice
    case rice_lake
    case richfield
    case richmond
    case richville
    case riverton
    case robbinsdale
    case rochester
    case rock_creek
    case rockford
    case rockville
    case rogers
    case rollingstone
    case roosevelt
    case roscoe
    case rose_creek
    case roseau
    case rosemount
    case roseville
    case rothsay
    case round_lake
    case royalton
    case rush_city
    case rushford
    case rushford_village
    case rushmore
    case russell
    case ruthton
    case rutledge
    
    case sabin
    case sacred_heart
    case saint_paul
    case sanborn
    case sandstone
    case sargeant
    case sartell
    case sauk_centre
    case sauk_rapids
    case savage
    case scandia
    case scanlon
    case seaforth
    case sebeka
    case sedan
    case shafer
    case shakopee
    case shelly
    case sherburn
    case shevlin
    case shoreview
    case shorewood
    case silver_bay
    case silver_lake
    case skyline
    case slayton
    case sleepy_eye
    case sobieski
    case solway
    case south_haven
    case south_st_paul
    case spicer
    case spring_grove
    case spring_hill
    case spring_lake_park
    case spring_park
    case spring_valley
    case springfield
    case squaw_lake
    case st_anthony
    case st_anthony_village
    case st_augusta
    case st_bonifacius
    case st_charles
    case st_clair
    case st_cloud
    case st_francis
    case st_hilaire
    case st_james
    case st_joseph
    case st_leo
    case st_louis_park
    case st_martin
    case st_marys_point
    case st_michael
    case st_paul_park
    case st_peter
    case st_rosa
    case st_stephen
    case st_vincent
    case stacy
    case staples
    case starbuck
    case steen
    case stephen
    case stewart
    case stewartville
    case stillwater
    case stockton
    case storden
    case strandquist
    case strathcona
    case sturgeon_lake
    case sunburg
    case sunfish_lake
    case swanville
    
    case taconite
    case tamarack
    case taopi
    case taunton
    case taylors_falls
    case tenstrike
    case thief_river_falls
    case tintah
    case tonka_bay
    case tower
    case tracy
    case trail
    case trimont
    case trommald
    case trosky
    case truman
    case turtle_river
    case twin_lakes
    case twin_valley
    case two_harbors
    case tyler
    
    case ulen
    case underwood
    case upsala
    case urbank
    case utica
    
    case vadnais_heights
    case vergas
    case vermillion
    case verndale
    case vernon_center
    case vesta
    case victoria
    case viking
    case villard
    case vining
    case virginia
    
    case wabasha
    case wabasso
    case waconia
    case wadena
    case wahkon
    case waite_park
    case waldorf
    case walker
    case walnut_grove
    case walters
    case waltham
    case wanamingo
    case wanda
    case warba
    case warren
    case warroad
    case waseca
    case watertown
    case waterville
    case watkins
    case watson
    case waubun
    case waverly
    case wayzata
    case welcome
    case wells
    case wendell
    case west_concord
    case west_st_paul
    case west_union
    case westbrook
    case westport
    case whalan
    case wheaton
    case white_bear_lake
    case wilder
    case willernie
    case williams
    case willmar
    case willow_river
    case wilmont
    case wilton
    case windom
    case winger
    case winnebago
    case winona
    case winsted
    case winthrop
    case winton
    case wolf_lake
    case wolverton
    case wood_lake
    case woodbury
    case woodland
    case woodstock
    case worthington
    case wrenshall
    case wright
    case wykoff
    case wyoming
    
    case zemple
    case zimmerman
    case zumbro_falls
    case zumbrota
    
    public func getSubdivision() -> any SovereignStateSubdivision {
        return SubdivisionsUnitedStates.minnesota
    }
    
    public func getShortNameDecimalSeparatorIndex() -> Int? {
        switch self {
        case .lake_st_croix_beach,
                .north_st_paul,
                .south_st_paul,
                .west_st_paul:
            return 1
        case .marine_on_st_croix:
            return 2
        default:
            return nil
        }
    }
}
