//
//  SovereignStateFlagEmoji.swift
//  
//
//  Created by Evan Anderson on 6/14/22.
//

import Foundation

internal enum SovereignStateFlagEmoji {
    static func get(_ country: Country) -> String? {
        switch country {
        case .artsakh: return nil
        case .abkhazia: return nil
        case .northern_cyprus: return nil
        case .somaliland: return nil
        case .transnistria: return nil

        case .afghanistan: return "🇦🇫"
        case .albania: return "🇦🇱"
        case .algeria: return "🇩🇿"
        case .american_samoa: return "🇦🇸"
        case .andorra: return "🇦🇩"
        case .angola: return "🇦🇴"
        case .anguilla: return "🇦🇮"
        case .antigua_and_barbuda: return "🇦🇬"
        case .argentina: return "🇦🇷"
        case .armenia: return "🇦🇲"
        case .aruba: return "🇦🇼"
        case .australia: return "🇦🇺"
        case .austria: return "🇦🇹"
        case .azerbaijan: return "🇦🇿"

        case .bahamas: return "🇧🇸"
        case .bahrain: return "🇧🇭"
        case .bangladesh: return "🇧🇩"
        case .barbados: return "🇧🇧"
        case .belarus: return "🇧🇾"
        case .belgium: return "🇧🇪"
        case .belize: return "🇧🇿"
        case .benin: return "🇧🇯"
        case .bermuda: return "🇧🇲"
        case .bhutan: return "🇧🇹"
        case .bolivia: return "🇧🇴"
        case .bosnia_and_herzegovina: return "🇧🇦"
        case .botswana: return "🇧🇼"
        case .brazil: return "🇧🇷"
        case .british_virgin_islands: return "🇻🇬"
        case .brunei: return "🇧🇳"
        case .bulgaria: return "🇧🇬"
        case .burkina_faso: return "🇧🇫"
        case .burundi: return "🇧🇮"

        case .cambodia: return "🇰🇭"
        case .cameroon: return "🇨🇲"
        case .canada: return "🇨🇦"
        case .cape_verde: return "🇨🇻"
        case .cayman_islands: return "🇰🇾"
        case .central_african_republic: return "🇨🇫"
        case .chad: return "🇹🇩"
        case .chile: return "🇨🇱"
        case .china: return "🇨🇳"
        case .colombia: return "🇨🇴"
        case .comoros: return "🇰🇲"
        case .cook_islands: return "🇨🇰"
        case .costa_rica: return "🇨🇷"
        case .croatia: return "🇭🇷"
        case .cuba: return "🇨🇺"
        case .curacao: return "🇨🇼"
        case .cyprus: return "🇨🇾"
        case .czech_republic: return "🇨🇿"

        case .democratic_republic_of_the_congo: return "🇨🇩"
        case .denmark: return "🇩🇰"
        case .djibouti: return "🇩🇯"
        case .dominica: return "🇩🇲"
        case .dominican_republic: return "🇩🇴"

        case .ecuador: return "🇪🇨"
        case .egypt: return "🇪🇬"
        case .el_salvador: return "🇸🇻"
        case .equatorial_guinea: return "🇬🇶"
        case .eritrea: return "🇪🇷"
        case .estonia: return "🇪🇪"
        case .eswatini: return "🇸🇿"
        case .ethiopia: return "🇪🇹"

        case .falkland_islands: return "🇫🇰"
        case .faroe_islands: return "🇫🇴"
        case .fiji: return "🇫🇯"
        case .finland: return "🇫🇮"
        case .france: return "🇫🇷"
        case .french_polynesia: return "🇵🇫"

        case .gabon: return "🇬🇦"
        case .gambia: return "🇬🇲"
        case .germany: return "🇩🇪"
        case .ghana: return "🇬🇭"
        case .gibraltar: return "🇬🇮"
        case .greece: return "🇬🇷"
        case .georgia: return "🇬🇪"
        case .greenland: return "🇬🇱"
        case .grenada: return "🇬🇩"
        case .guadeloupe: return "🇬🇵"
        case .guam: return "🇬🇺"
        case .guatemala: return "🇬🇹"
        case .guernsey: return "🇬🇬"
        case .guinea: return "🇬🇳"
        case .guinea_bissau: return "🇬🇼"
        case .guyana: return "🇬🇾"

        case .haiti: return "🇭🇹"
        case .honduras: return "🇭🇳"
        case .hong_kong: return "🇭🇰"
        case .hungary: return "🇭🇺"

        case .iceland: return "🇮🇸"
        case .india: return "🇮🇳"
        case .indonesia: return "🇮🇩"
        case .iran: return "🇮🇷"
        case .iraq: return "🇮🇶"
        case .ireland: return "🇮🇪"
        case .israel: return "🇮🇱"
        case .isle_of_man: return "🇮🇲"
        case .italy: return "🇮🇹"
        case .ivory_coast: return "🇨🇮"

        case .jamaica: return "🇯🇲"
        case .japan: return "🇯🇵"
        case .jersey: return "🇯🇪"
        case .jordan: return "🇯🇴"

        case .kazakhstan: return "🇰🇿"
        case .kenya: return "🇰🇪"
        case .kiribati: return "🇰🇮"
        case .kosovo: return "🇽🇰"
        case .kuwait: return "🇰🇼"
        case .kyrgyzstan: return "🇰🇬"

        case .laos: return "🇱🇦"
        case .latvia: return "🇱🇻"
        case .lebanon: return "🇱🇧"
        case .lesotho: return "🇱🇸"
        case .liberia: return "🇱🇷"
        case .libya: return "🇱🇾"
        case .liechtenstein: return "🇱🇮"
        case .lithuania: return "🇱🇹"
        case .luxembourg: return "🇱🇺"

        case .macau: return "🇲🇴"
        case .madagascar: return "🇲🇬"
        case .malawi: return "🇲🇼"
        case .malaysia: return "🇲🇾"
        case .maldives: return "🇲🇻"
        case .mali: return "🇲🇱"
        case .malta: return "🇲🇹"
        case .marshall_islands: return "🇲🇭"
        case .mauritania: return "🇲🇷"
        case .mauritius: return "🇲🇺"
        case .mexico: return "🇲🇽"
        case .micronesia: return "🇫🇲"
        case .moldova: return "🇲🇩"
        case .monaco: return "🇲🇨"
        case .mongolia: return "🇲🇳"
        case .montenegro: return "🇲🇪"
        case .montserrat: return "🇲🇸"
        case .morocco: return "🇲🇦"
        case .mozambique: return "🇲🇿"
        case .myanmar: return "🇲🇲"

        case .namibia: return "🇳🇦"
        case .nauru: return "🇳🇷"
        case .nepal: return "🇳🇵"
        case .netherlands: return "🇳🇱"
        case .new_caledonia: return "🇳🇨"
        case .new_zealand: return "🇳🇿"
        case .nicaragua: return "🇳🇮"
        case .niger: return "🇳🇪"
        case .nigeria: return "🇳🇬"
        case .niue: return "🇳🇺"
        case .norfolk_island: return "🇳🇫"
        case .north_korea: return "🇰🇵"
        case .north_macedonia: return "🇲🇰"
        case .northern_mariana_islands: return "🇲🇵"
        case .norway: return "🇳🇴"

        case .oman: return "🇴🇲"

        case .pakistan: return "🇵🇰"
        case .palau: return "🇵🇼"
        case .palestine: return "🇵🇸"
        case .panama: return "🇵🇦"
        case .papua_new_guinea: return "🇵🇬"
        case .paraguay: return "🇵🇾"
        case .peru: return "🇵🇪"
        case .philippines: return "🇵🇭"
        case .poland: return "🇵🇱"
        case .portugal: return "🇵🇹"
        case .puerto_rico: return "🇵🇷"

        case .qatar: return "🇶🇦"

        case .republic_of_the_congo: return "🇨🇬"
        case .romania: return "🇷🇴"
        case .russia: return "🇷🇺"
        case .rwanda: return "🇷🇼"

        case .saint_barthelemy: return "🇧🇱"
        case .saint_kitts_and_nevis: return "🇰🇳"
        case .saint_helena_ascension_and_tristan_da_cunha: return "🇸🇭"
        case .saint_lucia: return "🇱🇨"
        case .saint_martin: return "🇲🇫"
        case .saint_pierre_and_miquelon: return "🇵🇲"
        case .saint_vincent_and_the_grenadines: return "🇻🇨"
        case .samoa: return "🇼🇸"
        case .san_marino: return "🇸🇲"
        case .sao_tome_and_principe: return "🇸🇹"
        case .saudi_arabia: return "🇸🇦"
        case .scotland: return "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
        case .serbia: return "🇷🇸"
        case .senegal: return "🇸🇳"
        case .seychelles: return "🇸🇨"
        case .sierra_leone: return "🇸🇱"
        case .singapore: return "🇸🇬"
        case .slovakia: return "🇸🇰"
        case .slovenia: return "🇸🇮"
        case .solomon_islands: return "🇸🇧"
        case .somalia: return "🇸🇴"
        case .south_africa: return "🇿🇦"
        case .south_korea: return "🇰🇷"
        case .south_sudan: return "🇸🇸"
        case .spain: return "🇪🇸"
        case .sri_lanka: return "🇱🇰"
        case .sudan: return "🇸🇩"
        case .suriname: return "🇸🇷"
        case .sweden: return "🇸🇪"
        case .switzerland: return "🇨🇭"
        case .syria: return "🇸🇾"

        case .taiwan: return "🇹🇼"
        case .tajikistan: return "🇹🇯"
        case .tanzania: return "🇹🇿"
        case .thailand: return "🇹🇭"
        case .timor_leste: return "🇹🇱"
        case .togo: return "🇹🇬"
        case .tokelau: return "🇹🇰"
        case .tonga: return "🇹🇴"
        case .trinidad_and_tobago: return "🇹🇹"
        case .tunisia: return "🇹🇳"
        case .turkey: return "🇹🇷"
        case .turkmenistan: return "🇹🇲"
        case .turks_and_caicos_islands: return "🇹🇨"
        case .tuvalu: return "🇹🇻"

        case .uganda: return "🇺🇬"
        case .ukraine: return "🇺🇦"
        case .united_arab_emirates: return "🇦🇪"
        case .united_kingdom: return "🇬🇧"
        case .united_states: return "🇺🇸"
        case .united_states_virgin_islands: return "🇻🇮"
        case .uruguay: return "🇺🇾"
        case .uzbekistan: return "🇺🇿"

        case .vanuatu: return "🇻🇺"
        case .vatican_city: return "🇻🇦"
        case .venezuela: return "🇻🇪"
        case .vietnam: return "🇻🇳"

        case .wallis_and_futuna: return "🇼🇫"
        case .western_sahara: return "🇪🇭"

        case .yemen: return "🇾🇪"

        case .zambia: return "🇿🇲"
        case .zimbabwe: return "🇿🇼"
        }
    }
}
