//
//  SovereignStateNeighbors.swift
//  
//
//  Created by Evan Anderson on 7/9/22.
//

import Foundation

public extension Locale.Region { // https://en.wikipedia.org/wiki/List_of_countries_and_territories_by_land_and_maritime_borders
    var neighbors : [Locale.Region]? {
        switch self {
        case .abkhazia: return [Locale.Region.russia, Locale.Region.georgia, Locale.Region.turkey]
        case .afghanistan: return [Locale.Region.chinaMainland, Locale.Region.iran, Locale.Region.pakistan, Locale.Region.tajikistan, Locale.Region.turkmenistan, Locale.Region.uzbekistan]
        case .albania: return [Locale.Region.greece, Locale.Region.italy, Locale.Region.kosovo, Locale.Region.montenegro, Locale.Region.northMacedonia]
        case .algeria: return [Locale.Region.france, Locale.Region.italy, Locale.Region.libya, Locale.Region.mali, Locale.Region.mauritania, Locale.Region.morocco, Locale.Region.niger, Locale.Region.spain, Locale.Region.tunisia, Locale.Region.westernSahara]
        case .americanSamoa: return [Locale.Region.cookIslands, Locale.Region.niue, Locale.Region.tokelau, Locale.Region.tonga]
        case .andorra: return [Locale.Region.france, Locale.Region.spain]
        case .angola: return [Locale.Region.congoKinshasa, Locale.Region.congoBrazzaville, Locale.Region.namibia, Locale.Region.zambia]
        case .anguilla: return [Locale.Region.antiguaBarbuda, Locale.Region.britishVirginIslands, Locale.Region.netherlands, Locale.Region.saintBarthélemy, Locale.Region.saintMartin]

        case .antiguaBarbuda: return [Locale.Region.anguilla, Locale.Region.france, Locale.Region.montserrat, Locale.Region.saintBarthélemy, Locale.Region.saintKittsNevis]
        case .argentina: return [Locale.Region.bolivia, Locale.Region.brazil, Locale.Region.chile, Locale.Region.falklandIslands, Locale.Region.paraguay, Locale.Region.uruguay]
        case .artsakh: return [Locale.Region.armenia, Locale.Region.azerbaijan]
        case .armenia: return [Locale.Region.azerbaijan, Locale.Region.georgia, Locale.Region.iran, Locale.Region.turkey]
        case .aruba: return [Locale.Region.dominicanRepublic, Locale.Region.venezuela]
        case .australia: return [Locale.Region.indonesia, Locale.Region.newZealand, Locale.Region.papuaNewGuinea, Locale.Region.solomonIslands, Locale.Region.timorLeste]
        case .austria: return [Locale.Region.czechia, Locale.Region.germany, Locale.Region.hungary, Locale.Region.italy, Locale.Region.liechtenstein, Locale.Region.slovakia, Locale.Region.slovenia, Locale.Region.switzerland]
        case .azerbaijan: return [Locale.Region.armenia, Locale.Region.georgia, Locale.Region.iran, Locale.Region.kazakhstan, Locale.Region.russia, Locale.Region.turkey, Locale.Region.turkmenistan]

        case .bahamas: return [Locale.Region.cuba, Locale.Region.haiti, Locale.Region.turksCaicosIslands, Locale.Region.unitedStates]
        case .bahrain: return [Locale.Region.iran, Locale.Region.qatar, Locale.Region.saudiArabia]
        case .bangladesh: return [Locale.Region.india, Locale.Region.myanmar]
        case .barbados: return [Locale.Region.france, Locale.Region.guyana, Locale.Region.saintLucia, Locale.Region.saintVincentGrenadines, Locale.Region.trinidadTobago, Locale.Region.venezuela]
        case .belarus: return [Locale.Region.latvia, Locale.Region.lithuania, Locale.Region.poland, Locale.Region.russia, Locale.Region.ukraine]
        case .belgium: return [Locale.Region.france, Locale.Region.germany, Locale.Region.luxembourg, Locale.Region.netherlands, Locale.Region.unitedKingdom]
        case .belize: return [Locale.Region.guatemala, Locale.Region.honduras, Locale.Region.mexico]
        case .benin: return [Locale.Region.burkinaFaso, Locale.Region.niger, Locale.Region.nigeria, Locale.Region.togo]
        case .bermuda: return nil
        case .bhutan: return [Locale.Region.chinaMainland, Locale.Region.india]
        case .bolivia: return [Locale.Region.argentina, Locale.Region.brazil, Locale.Region.chile, Locale.Region.paraguay, Locale.Region.peru]
        case .bosniaHerzegovina: return [Locale.Region.croatia, Locale.Region.montenegro, Locale.Region.serbia]
        case .botswana: return [Locale.Region.namibia, Locale.Region.southAfrica, Locale.Region.zambia, Locale.Region.zimbabwe]
        case .brazil: return [Locale.Region.argentina, Locale.Region.bolivia, Locale.Region.colombia, Locale.Region.france, Locale.Region.guyana, Locale.Region.paraguay, Locale.Region.peru, Locale.Region.suriname, Locale.Region.uruguay, Locale.Region.venezuela]
        case .britishVirginIslands: return [Locale.Region.anguilla, Locale.Region.puertoRico]
        case .brunei: return [Locale.Region.chinaMainland, Locale.Region.malaysia, Locale.Region.philippines, Locale.Region.taiwan, Locale.Region.vietnam]
        case .bulgaria: return [Locale.Region.georgia, Locale.Region.greece, Locale.Region.northMacedonia, Locale.Region.romania, Locale.Region.serbia, Locale.Region.turkey]
        case .burkinaFaso: return [Locale.Region.benin, Locale.Region.côteDIvoire, Locale.Region.ghana, Locale.Region.mali, Locale.Region.niger, Locale.Region.togo]
        case .burundi: return [Locale.Region.congoKinshasa, Locale.Region.rwanda, Locale.Region.tanzania]

        case .cambodia: return [Locale.Region.laos, Locale.Region.thailand, Locale.Region.vietnam]
        case .cameroon: return [Locale.Region.centralAfricanRepublic, Locale.Region.chad, Locale.Region.congoBrazzaville, Locale.Region.gabon, Locale.Region.nigeria]
        case .canada: return [Locale.Region.greenland, Locale.Region.saintPierreMiquelon, Locale.Region.unitedStates]
        case .capeVerde: return [Locale.Region.gambia, Locale.Region.mauritania, Locale.Region.senegal]
        case .caymanIslands: return [Locale.Region.cuba, Locale.Region.honduras, Locale.Region.jamaica]
        case .centralAfricanRepublic: return [Locale.Region.cameroon, Locale.Region.chad, Locale.Region.congoKinshasa, Locale.Region.congoBrazzaville, Locale.Region.southSudan, Locale.Region.sudan]
        case .chad: return [Locale.Region.cameroon, Locale.Region.centralAfricanRepublic, Locale.Region.libya, Locale.Region.niger, Locale.Region.nigeria, Locale.Region.sudan]
        case .chile: return [Locale.Region.argentina, Locale.Region.bolivia, Locale.Region.peru]
        case .chinaMainland: return [Locale.Region.afghanistan, Locale.Region.bhutan, Locale.Region.brunei, Locale.Region.hongKong, Locale.Region.india, Locale.Region.indonesia, Locale.Region.japan, Locale.Region.kazakhstan, Locale.Region.northKorea, Locale.Region.southKorea, Locale.Region.kyrgyzstan, Locale.Region.laos, Locale.Region.macao, Locale.Region.malaysia, Locale.Region.mongolia, Locale.Region.myanmar, Locale.Region.nepal, Locale.Region.pakistan, Locale.Region.philippines, Locale.Region.russia, Locale.Region.taiwan, Locale.Region.tajikistan, Locale.Region.vietnam]
        case .colombia: return [Locale.Region.brazil, Locale.Region.costaRica, Locale.Region.dominicanRepublic, Locale.Region.ecuador, Locale.Region.haiti, Locale.Region.jamaica, Locale.Region.nicaragua, Locale.Region.panama, Locale.Region.peru, Locale.Region.venezuela]
        case .comoros: return [Locale.Region.france, Locale.Region.madagascar, Locale.Region.mozambique, Locale.Region.seychelles, Locale.Region.tanzania]
        case .cookIslands: return [Locale.Region.americanSamoa, Locale.Region.kiribati, Locale.Region.niue, Locale.Region.tokelau]
        case .congoKinshasa: return [Locale.Region.angola, Locale.Region.burundi, Locale.Region.centralAfricanRepublic, Locale.Region.congoBrazzaville, Locale.Region.rwanda, Locale.Region.southSudan, Locale.Region.tanzania, Locale.Region.uganda, Locale.Region.zambia]
        case .congoBrazzaville: return [Locale.Region.angola, Locale.Region.cameroon, Locale.Region.centralAfricanRepublic, Locale.Region.congoKinshasa, Locale.Region.gabon]
        case .costaRica: return [Locale.Region.colombia, Locale.Region.ecuador, Locale.Region.nicaragua, Locale.Region.panama]
        case .côteDIvoire: return [Locale.Region.burkinaFaso, Locale.Region.ghana, Locale.Region.guinea, Locale.Region.liberia, Locale.Region.mali]
        case .croatia: return [Locale.Region.bosniaHerzegovina, Locale.Region.hungary, Locale.Region.italy, Locale.Region.montenegro, Locale.Region.serbia, Locale.Region.slovenia]
        case .cuba: return [Locale.Region.bahamas, Locale.Region.caymanIslands, Locale.Region.haiti, Locale.Region.honduras, Locale.Region.jamaica, Locale.Region.mexico, Locale.Region.unitedStates]
        case .cyprus: return [Locale.Region.egypt, Locale.Region.greece, Locale.Region.israel, Locale.Region.lebanon, Locale.Region.northernCyprus, Locale.Region.syria, Locale.Region.turkey]
        case .czechia: return [Locale.Region.austria, Locale.Region.germany, Locale.Region.poland, Locale.Region.slovakia]

        case .denmark: return [Locale.Region.germany, Locale.Region.norway, Locale.Region.poland, Locale.Region.sweden, Locale.Region.unitedKingdom]
        case .djibouti: return [Locale.Region.eritrea, Locale.Region.ethiopia, Locale.Region.somaliland, Locale.Region.yemen]
        case .dominica: return [Locale.Region.france, Locale.Region.venezuela]
        case .dominicanRepublic: return [Locale.Region.aruba, Locale.Region.colombia, Locale.Region.haiti, Locale.Region.puertoRico, Locale.Region.turksCaicosIslands, Locale.Region.venezuela]

        case .timorLeste: return [Locale.Region.australia, Locale.Region.indonesia]
        case .ecuador: return [Locale.Region.colombia, Locale.Region.costaRica, Locale.Region.peru]
        case .egypt: return [Locale.Region.cyprus, Locale.Region.greece, Locale.Region.israel, Locale.Region.jordan, Locale.Region.libya, Locale.Region.saudiArabia, Locale.Region.sudan, Locale.Region.turkey, Locale.Region.palestine]
        case .elSalvador: return [Locale.Region.guatemala, Locale.Region.honduras, Locale.Region.nicaragua]
        case .eritrea: return [Locale.Region.djibouti, Locale.Region.ethiopia, Locale.Region.saudiArabia, Locale.Region.sudan, Locale.Region.yemen]
        case .estonia: return [Locale.Region.finland, Locale.Region.latvia, Locale.Region.russia, Locale.Region.sweden]
        case .eswatini: return [Locale.Region.mozambique, Locale.Region.southAfrica]
        case .ethiopia: return [Locale.Region.djibouti, Locale.Region.eritrea, Locale.Region.kenya, Locale.Region.somaliland, Locale.Region.southSudan, Locale.Region.sudan]

        case .falklandIslands: return [Locale.Region.argentina]
        case .fiji: return [Locale.Region.newZealand, Locale.Region.solomonIslands, Locale.Region.tonga, Locale.Region.tuvalu, Locale.Region.vanuatu, Locale.Region.wallisFutuna]
        case .finland: return [Locale.Region.estonia, Locale.Region.norway, Locale.Region.russia, Locale.Region.sweden]
        case .france: return [Locale.Region.algeria, Locale.Region.andorra, Locale.Region.antiguaBarbuda, Locale.Region.barbados, Locale.Region.belgium, Locale.Region.brazil, Locale.Region.comoros, Locale.Region.dominica, Locale.Region.germany, Locale.Region.guernsey, Locale.Region.italy, Locale.Region.jersey, Locale.Region.luxembourg, Locale.Region.madagascar, Locale.Region.mauritius, Locale.Region.monaco, Locale.Region.montserrat, Locale.Region.saintLucia, Locale.Region.spain, Locale.Region.switzerland, Locale.Region.suriname, Locale.Region.unitedKingdom, Locale.Region.venezuela]

        case .gabon: return [Locale.Region.cameroon, Locale.Region.congoBrazzaville, Locale.Region.sãoToméPríncipe]
        case .gambia: return [Locale.Region.senegal]
        case .georgia: return [Locale.Region.armenia, Locale.Region.azerbaijan, Locale.Region.bulgaria, Locale.Region.russia, Locale.Region.turkey]
        case .germany: return [Locale.Region.austria, Locale.Region.belgium, Locale.Region.czechia, Locale.Region.denmark, Locale.Region.france, Locale.Region.luxembourg, Locale.Region.netherlands, Locale.Region.poland, Locale.Region.sweden, Locale.Region.switzerland, Locale.Region.unitedKingdom]
        case .ghana: return [Locale.Region.burkinaFaso, Locale.Region.côteDIvoire, Locale.Region.togo]
        case .gibraltar: return [Locale.Region.spain]
        case .greece: return [Locale.Region.albania, Locale.Region.bulgaria, Locale.Region.cyprus, Locale.Region.egypt, Locale.Region.italy, Locale.Region.libya, Locale.Region.northMacedonia, Locale.Region.turkey]
        case .greenland: return [Locale.Region.canada, Locale.Region.iceland]
        case .grenada: return [Locale.Region.saintVincentGrenadines, Locale.Region.trinidadTobago, Locale.Region.venezuela]
        case .guam: return [Locale.Region.micronesia, Locale.Region.northernMarianaIslands]
        case .guatemala: return [Locale.Region.belize, Locale.Region.elSalvador, Locale.Region.honduras, Locale.Region.mexico]
        case .guernsey: return [Locale.Region.france, Locale.Region.jersey, Locale.Region.unitedKingdom]
        case .guinea: return [Locale.Region.côteDIvoire, Locale.Region.guineaBissau, Locale.Region.liberia, Locale.Region.mali, Locale.Region.senegal, Locale.Region.sierraLeone]
        case .guineaBissau: return [Locale.Region.guinea, Locale.Region.senegal]
        case .guyana: return [Locale.Region.barbados, Locale.Region.brazil, Locale.Region.suriname, Locale.Region.trinidadTobago, Locale.Region.venezuela]

        case .haiti: return [Locale.Region.colombia, Locale.Region.cuba, Locale.Region.dominicanRepublic, Locale.Region.jamaica, Locale.Region.turksCaicosIslands]
        case .honduras: return [Locale.Region.belize, Locale.Region.caymanIslands, Locale.Region.cuba, Locale.Region.elSalvador, Locale.Region.guatemala, Locale.Region.jamaica, Locale.Region.mexico, Locale.Region.nicaragua]
        case .hongKong: return [Locale.Region.chinaMainland, Locale.Region.macao]
        case .hungary: return [Locale.Region.austria, Locale.Region.croatia, Locale.Region.romania, Locale.Region.serbia, Locale.Region.slovakia, Locale.Region.slovenia, Locale.Region.ukraine]

        case .iceland: return [Locale.Region.faroeIslands, Locale.Region.greenland]
        case .india: return [Locale.Region.bangladesh, Locale.Region.bhutan, Locale.Region.chinaMainland, Locale.Region.indonesia, Locale.Region.maldives, Locale.Region.myanmar, Locale.Region.nepal, Locale.Region.pakistan, Locale.Region.sriLanka, Locale.Region.thailand]
        case .indonesia: return [Locale.Region.australia, Locale.Region.chinaMainland, Locale.Region.timorLeste, Locale.Region.india, Locale.Region.malaysia, Locale.Region.palau, Locale.Region.papuaNewGuinea, Locale.Region.philippines, Locale.Region.singapore, Locale.Region.taiwan, Locale.Region.thailand, Locale.Region.vietnam]
        case .iran: return [Locale.Region.afghanistan, Locale.Region.armenia, Locale.Region.azerbaijan, Locale.Region.bahrain, Locale.Region.iraq, Locale.Region.kazakhstan, Locale.Region.kuwait, Locale.Region.oman, Locale.Region.pakistan, Locale.Region.qatar, Locale.Region.russia, Locale.Region.saudiArabia, Locale.Region.turkey, Locale.Region.turkmenistan, Locale.Region.unitedArabEmirates]
        case .iraq: return [Locale.Region.iran, Locale.Region.jordan, Locale.Region.kuwait, Locale.Region.saudiArabia, Locale.Region.syria, Locale.Region.turkey]
        case .ireland: return [Locale.Region.unitedKingdom]
        case .israel: return [Locale.Region.cyprus, Locale.Region.egypt, Locale.Region.jordan, Locale.Region.lebanon, Locale.Region.palestine, Locale.Region.syria]
        case .italy: return [Locale.Region.albania, Locale.Region.algeria, Locale.Region.austria, Locale.Region.croatia, Locale.Region.france, Locale.Region.greece, Locale.Region.libya, Locale.Region.malta, Locale.Region.montenegro, Locale.Region.sanMarino, Locale.Region.slovenia, Locale.Region.spain, Locale.Region.switzerland, Locale.Region.tunisia, Locale.Region.vaticanCity]

        case .jamaica: return [Locale.Region.caymanIslands, Locale.Region.colombia, Locale.Region.cuba, Locale.Region.haiti, Locale.Region.honduras, Locale.Region.nicaragua]
        case .japan: return [Locale.Region.chinaMainland, Locale.Region.palau, Locale.Region.philippines, Locale.Region.russia, Locale.Region.southKorea, Locale.Region.northernMarianaIslands, Locale.Region.taiwan]
        case .jersey: return [Locale.Region.france, Locale.Region.guernsey]
        case .jordan: return [Locale.Region.egypt, Locale.Region.iraq, Locale.Region.israel, Locale.Region.palestine, Locale.Region.saudiArabia, Locale.Region.syria]

        case .kazakhstan: return [Locale.Region.azerbaijan, Locale.Region.chinaMainland, Locale.Region.kyrgyzstan, Locale.Region.russia, Locale.Region.turkmenistan, Locale.Region.uzbekistan]
        case .kenya: return [Locale.Region.ethiopia, Locale.Region.somalia, Locale.Region.southSudan, Locale.Region.tanzania, Locale.Region.uganda]
        case .kiribati: return [Locale.Region.cookIslands, Locale.Region.marshallIslands, Locale.Region.nauru, Locale.Region.tokelau, Locale.Region.tuvalu]
        case .kosovo: return [Locale.Region.albania, Locale.Region.montenegro, Locale.Region.northMacedonia, Locale.Region.serbia]
        case .kuwait: return [Locale.Region.iran, Locale.Region.iraq, Locale.Region.saudiArabia]
        case .kyrgyzstan: return [Locale.Region.chinaMainland, Locale.Region.kazakhstan, Locale.Region.tajikistan, Locale.Region.uzbekistan]

        case .laos: return [Locale.Region.cambodia, Locale.Region.chinaMainland, Locale.Region.myanmar, Locale.Region.thailand, Locale.Region.vietnam]
        case .latvia: return [Locale.Region.belarus, Locale.Region.estonia, Locale.Region.lithuania, Locale.Region.russia, Locale.Region.sweden]
        case .lebanon: return [Locale.Region.cyprus, Locale.Region.israel, Locale.Region.syria]
        case .lesotho: return [Locale.Region.southAfrica]
        case .liberia: return [Locale.Region.guinea, Locale.Region.côteDIvoire, Locale.Region.sierraLeone]
        case .libya: return [Locale.Region.algeria, Locale.Region.chad, Locale.Region.egypt, Locale.Region.greece, Locale.Region.italy, Locale.Region.malta, Locale.Region.niger, Locale.Region.sudan, Locale.Region.tunisia, Locale.Region.turkey]
        case .liechtenstein: return [Locale.Region.austria, Locale.Region.switzerland]
        case .lithuania: return [Locale.Region.belarus, Locale.Region.latvia, Locale.Region.poland, Locale.Region.russia, Locale.Region.sweden]
        case .luxembourg: return [Locale.Region.belgium, Locale.Region.france, Locale.Region.germany]

        case .macao: return [Locale.Region.chinaMainland, Locale.Region.hongKong]
        case .madagascar: return [Locale.Region.comoros, Locale.Region.france, Locale.Region.mauritius, Locale.Region.mozambique, Locale.Region.seychelles]
        case .malawi: return [Locale.Region.mozambique, Locale.Region.tanzania, Locale.Region.zambia]
        case .malaysia: return [Locale.Region.brunei, Locale.Region.chinaMainland, Locale.Region.indonesia, Locale.Region.philippines, Locale.Region.singapore, Locale.Region.taiwan, Locale.Region.thailand]
        case .maldives: return [Locale.Region.india, Locale.Region.sriLanka]
        case .mali: return [Locale.Region.algeria, Locale.Region.burkinaFaso, Locale.Region.côteDIvoire, Locale.Region.guinea, Locale.Region.mauritania, Locale.Region.niger, Locale.Region.senegal]
        case .malta: return [Locale.Region.italy, Locale.Region.libya, Locale.Region.tunisia]
        case .marshallIslands: return [Locale.Region.kiribati, Locale.Region.micronesia, Locale.Region.nauru]
        case .mauritania: return [Locale.Region.algeria, Locale.Region.capeVerde, Locale.Region.mali, Locale.Region.senegal, Locale.Region.westernSahara]
        case .mauritius: return [Locale.Region.france, Locale.Region.madagascar, Locale.Region.seychelles]
        case .mexico: return [Locale.Region.belize, Locale.Region.cuba, Locale.Region.guatemala, Locale.Region.honduras, Locale.Region.unitedStates]
        case .micronesia: return [Locale.Region.guam, Locale.Region.marshallIslands, Locale.Region.palau, Locale.Region.papuaNewGuinea]
        case .moldova: return [Locale.Region.romania, Locale.Region.ukraine]
        case .monaco: return [Locale.Region.france]
        case .mongolia: return [Locale.Region.chinaMainland, Locale.Region.russia]
        case .montenegro: return [Locale.Region.albania, Locale.Region.bosniaHerzegovina, Locale.Region.croatia, Locale.Region.italy, Locale.Region.kosovo, Locale.Region.serbia]
        case .montserrat: return [Locale.Region.antiguaBarbuda, Locale.Region.france, Locale.Region.saintKittsNevis, Locale.Region.venezuela]
        case .morocco: return [Locale.Region.algeria, Locale.Region.portugal, Locale.Region.spain, Locale.Region.westernSahara]
        case .mozambique: return [Locale.Region.comoros, Locale.Region.eswatini, Locale.Region.madagascar, Locale.Region.malawi, Locale.Region.southAfrica, Locale.Region.tanzania, Locale.Region.zambia, Locale.Region.zimbabwe]
        case .myanmar: return [Locale.Region.bangladesh, Locale.Region.chinaMainland, Locale.Region.india, Locale.Region.laos, Locale.Region.thailand]

        case .namibia: return [Locale.Region.angola, Locale.Region.botswana, Locale.Region.southAfrica, Locale.Region.zambia]
        case .nauru: return [Locale.Region.kiribati, Locale.Region.marshallIslands]
        case .nepal: return [Locale.Region.chinaMainland, Locale.Region.india]

        case .netherlands: return [Locale.Region.anguilla, Locale.Region.belgium, Locale.Region.germany, Locale.Region.saintBarthélemy, Locale.Region.saintMartin, Locale.Region.unitedKingdom, Locale.Region.venezuela]
        case .newZealand: return [Locale.Region.australia, Locale.Region.fiji, Locale.Region.norfolkIsland]
        case .nicaragua: return [Locale.Region.colombia, Locale.Region.costaRica, Locale.Region.elSalvador, Locale.Region.honduras, Locale.Region.jamaica, Locale.Region.panama]
        case .niger: return [Locale.Region.algeria, Locale.Region.benin, Locale.Region.burkinaFaso, Locale.Region.chad, Locale.Region.libya, Locale.Region.mali, Locale.Region.nigeria]
        case .nigeria: return [Locale.Region.benin, Locale.Region.cameroon, Locale.Region.chad, Locale.Region.niger, Locale.Region.sãoToméPríncipe]
        case .niue: return [Locale.Region.americanSamoa, Locale.Region.cookIslands, Locale.Region.tonga]
        case .norfolkIsland: return [Locale.Region.newZealand]
        case .northKorea: return [Locale.Region.chinaMainland, Locale.Region.southKorea, Locale.Region.russia]
        case .northMacedonia: return [Locale.Region.albania, Locale.Region.bulgaria, Locale.Region.greece, Locale.Region.kosovo, Locale.Region.serbia]
        case .northernCyprus: return [Locale.Region.cyprus, Locale.Region.syria, Locale.Region.turkey]
        case .northernMarianaIslands: return [Locale.Region.guam, Locale.Region.japan]
        case .norway: return [Locale.Region.denmark, Locale.Region.faroeIslands, Locale.Region.finland, Locale.Region.russia, Locale.Region.sweden, Locale.Region.unitedKingdom]

        case .oman: return [Locale.Region.iran, Locale.Region.pakistan, Locale.Region.saudiArabia, Locale.Region.unitedArabEmirates, Locale.Region.yemen]

        case .pakistan: return [Locale.Region.afghanistan, Locale.Region.chinaMainland, Locale.Region.india, Locale.Region.iran, Locale.Region.oman]
        case .palau: return [Locale.Region.indonesia, Locale.Region.japan, Locale.Region.micronesia, Locale.Region.philippines]
        case .palestine: return [Locale.Region.egypt, Locale.Region.israel, Locale.Region.jordan]
        case .panama: return [Locale.Region.colombia, Locale.Region.costaRica, Locale.Region.nicaragua]
        case .papuaNewGuinea: return [Locale.Region.australia, Locale.Region.indonesia, Locale.Region.micronesia, Locale.Region.solomonIslands]
        case .paraguay: return [Locale.Region.argentina, Locale.Region.bolivia, Locale.Region.brazil]
        case .peru: return [Locale.Region.bolivia, Locale.Region.brazil, Locale.Region.chile, Locale.Region.colombia, Locale.Region.ecuador]
        case .philippines: return [Locale.Region.brunei, Locale.Region.chinaMainland, Locale.Region.indonesia, Locale.Region.japan, Locale.Region.malaysia, Locale.Region.palau, Locale.Region.taiwan, Locale.Region.vietnam]
        case .poland: return [Locale.Region.belarus, Locale.Region.czechia, Locale.Region.denmark, Locale.Region.germany, Locale.Region.lithuania, Locale.Region.russia, Locale.Region.slovakia, Locale.Region.sweden, Locale.Region.ukraine]
        case .portugal: return [Locale.Region.morocco, Locale.Region.spain]
        case .puertoRico: return [Locale.Region.britishVirginIslands, Locale.Region.dominicanRepublic, Locale.Region.venezuela]

        case .qatar: return [Locale.Region.bahrain, Locale.Region.iran, Locale.Region.saudiArabia, Locale.Region.unitedArabEmirates]

        case .romania: return [Locale.Region.bulgaria, Locale.Region.hungary, Locale.Region.moldova, Locale.Region.russia, Locale.Region.serbia, Locale.Region.ukraine]
        case .russia: return [Locale.Region.azerbaijan, Locale.Region.belarus, Locale.Region.chinaMainland, Locale.Region.estonia, Locale.Region.finland, Locale.Region.georgia, Locale.Region.iran, Locale.Region.japan, Locale.Region.kazakhstan, Locale.Region.northKorea, Locale.Region.latvia, Locale.Region.lithuania, Locale.Region.mongolia, Locale.Region.norway, Locale.Region.poland, Locale.Region.romania, Locale.Region.sweden, Locale.Region.turkey, Locale.Region.ukraine, Locale.Region.unitedStates]
        case .rwanda: return [Locale.Region.burundi, Locale.Region.congoKinshasa, Locale.Region.tanzania, Locale.Region.uganda]

        case .saintBarthélemy: return [Locale.Region.anguilla, Locale.Region.antiguaBarbuda, Locale.Region.netherlands, Locale.Region.saintKittsNevis, Locale.Region.saintMartin]
        case .saintHelena: return nil
        case .saintKittsNevis: return [Locale.Region.antiguaBarbuda, Locale.Region.montserrat, Locale.Region.netherlands, Locale.Region.saintBarthélemy, Locale.Region.venezuela]
        case .saintLucia: return [Locale.Region.barbados, Locale.Region.france, Locale.Region.saintVincentGrenadines, Locale.Region.venezuela]
        case .saintPierreMiquelon: return [Locale.Region.canada]
        case .saintMartin: return [Locale.Region.anguilla, Locale.Region.netherlands, Locale.Region.saintBarthélemy]
        case .saintVincentGrenadines: return [Locale.Region.barbados, Locale.Region.grenada, Locale.Region.saintLucia, Locale.Region.trinidadTobago, Locale.Region.venezuela]
        case .samoa: return [Locale.Region.americanSamoa, Locale.Region.tokelau, Locale.Region.tonga, Locale.Region.wallisFutuna]
        case .sanMarino: return [Locale.Region.italy]
        case .sãoToméPríncipe: return [Locale.Region.gabon, Locale.Region.nigeria]
        case .saudiArabia: return [Locale.Region.bahrain, Locale.Region.egypt, Locale.Region.eritrea, Locale.Region.iran, Locale.Region.iraq, Locale.Region.jordan, Locale.Region.kuwait, Locale.Region.oman, Locale.Region.qatar, Locale.Region.sudan, Locale.Region.unitedArabEmirates, Locale.Region.yemen]
        case .senegal: return [Locale.Region.capeVerde, Locale.Region.gambia, Locale.Region.guinea, Locale.Region.guineaBissau, Locale.Region.mali, Locale.Region.mauritania]
        case .serbia: return [Locale.Region.bosniaHerzegovina, Locale.Region.bulgaria, Locale.Region.croatia, Locale.Region.hungary, Locale.Region.kosovo, Locale.Region.montenegro, Locale.Region.northMacedonia, Locale.Region.romania]
        case .seychelles: return [Locale.Region.comoros, Locale.Region.madagascar, Locale.Region.mauritius, Locale.Region.tanzania]
        case .sierraLeone: return [Locale.Region.guinea, Locale.Region.liberia]
        case .singapore: return [Locale.Region.indonesia, Locale.Region.malaysia]
        case .slovakia: return [Locale.Region.austria, Locale.Region.czechia, Locale.Region.hungary, Locale.Region.poland, Locale.Region.ukraine]
        case .slovenia: return [Locale.Region.austria, Locale.Region.croatia, Locale.Region.italy, Locale.Region.hungary]
        case .solomonIslands: return [Locale.Region.fiji, Locale.Region.papuaNewGuinea, Locale.Region.vanuatu]
        case .somalia: return [Locale.Region.djibouti, Locale.Region.ethiopia, Locale.Region.kenya, Locale.Region.yemen]
        case .somaliland: return [Locale.Region.djibouti, Locale.Region.ethiopia, Locale.Region.somalia, Locale.Region.yemen]
        case .southAfrica: return [Locale.Region.botswana, Locale.Region.eswatini, Locale.Region.lesotho, Locale.Region.mozambique, Locale.Region.namibia, Locale.Region.zimbabwe]
        case .southKorea: return [Locale.Region.chinaMainland, Locale.Region.japan, Locale.Region.northKorea]
        case .southSudan: return [Locale.Region.centralAfricanRepublic, Locale.Region.congoKinshasa, Locale.Region.ethiopia, Locale.Region.kenya, Locale.Region.sudan, Locale.Region.uganda]
        case .spain: return [Locale.Region.algeria, Locale.Region.andorra, Locale.Region.france, Locale.Region.italy, Locale.Region.gibraltar, Locale.Region.morocco, Locale.Region.portugal, Locale.Region.westernSahara]
        case .sriLanka: return [Locale.Region.india, Locale.Region.maldives]
        case .sudan: return [Locale.Region.centralAfricanRepublic, Locale.Region.chad, Locale.Region.egypt, Locale.Region.eritrea, Locale.Region.ethiopia, Locale.Region.libya, Locale.Region.saudiArabia, Locale.Region.southSudan]
        case .suriname: return [Locale.Region.brazil, Locale.Region.france, Locale.Region.guyana]
        case .sweden: return [Locale.Region.denmark, Locale.Region.estonia, Locale.Region.finland, Locale.Region.germany, Locale.Region.latvia, Locale.Region.lithuania, Locale.Region.norway, Locale.Region.poland, Locale.Region.russia]
        case .switzerland: return [Locale.Region.austria, Locale.Region.france, Locale.Region.italy, Locale.Region.liechtenstein, Locale.Region.germany]
        case .syria: return [Locale.Region.cyprus, Locale.Region.iraq, Locale.Region.israel, Locale.Region.jordan, Locale.Region.lebanon, Locale.Region.northernCyprus, Locale.Region.turkey]
        case .taiwan: return [Locale.Region.brunei, Locale.Region.chinaMainland, Locale.Region.indonesia, Locale.Region.japan, Locale.Region.malaysia, Locale.Region.philippines, Locale.Region.vietnam]
        case .tajikistan: return [Locale.Region.afghanistan, Locale.Region.chinaMainland, Locale.Region.kyrgyzstan, Locale.Region.uzbekistan]
        case .tanzania: return [Locale.Region.burundi, Locale.Region.comoros, Locale.Region.congoKinshasa, Locale.Region.kenya, Locale.Region.malawi, Locale.Region.mozambique, Locale.Region.rwanda, Locale.Region.seychelles, Locale.Region.uganda, Locale.Region.zambia]
        case .thailand: return [Locale.Region.cambodia, Locale.Region.india, Locale.Region.indonesia, Locale.Region.laos, Locale.Region.malaysia, Locale.Region.myanmar, Locale.Region.vietnam]
        case .togo: return [Locale.Region.benin, Locale.Region.burkinaFaso, Locale.Region.ghana]
        case .tokelau: return [Locale.Region.americanSamoa, Locale.Region.cookIslands, Locale.Region.kiribati, Locale.Region.samoa, Locale.Region.wallisFutuna]
        case .tonga: return [Locale.Region.americanSamoa, Locale.Region.fiji, Locale.Region.niue, Locale.Region.samoa, Locale.Region.wallisFutuna]
        case .transnistria: return [Locale.Region.moldova, Locale.Region.ukraine]
        case .trinidadTobago: return [Locale.Region.barbados, Locale.Region.grenada, Locale.Region.guyana, Locale.Region.saintVincentGrenadines, Locale.Region.venezuela]
        case .tunisia: return [Locale.Region.algeria, Locale.Region.italy, Locale.Region.libya, Locale.Region.malta]
        case .turkey: return [Locale.Region.armenia, Locale.Region.azerbaijan, Locale.Region.bulgaria, Locale.Region.cyprus, Locale.Region.egypt, Locale.Region.georgia, Locale.Region.greece, Locale.Region.iran, Locale.Region.iraq, Locale.Region.northernCyprus, Locale.Region.russia, Locale.Region.syria, Locale.Region.ukraine, Locale.Region.libya]
        case .turkmenistan: return [Locale.Region.afghanistan, Locale.Region.azerbaijan, Locale.Region.iran, Locale.Region.kazakhstan, Locale.Region.uzbekistan]
        case .turksCaicosIslands: return [Locale.Region.bahamas, Locale.Region.dominicanRepublic, Locale.Region.haiti]
        case .tuvalu: return [Locale.Region.fiji, Locale.Region.kiribati, Locale.Region.wallisFutuna]

        case .uganda: return [Locale.Region.congoKinshasa, Locale.Region.kenya, Locale.Region.rwanda, Locale.Region.southSudan, Locale.Region.tanzania]
        case .ukraine: return [Locale.Region.belarus, Locale.Region.hungary, Locale.Region.moldova, Locale.Region.poland, Locale.Region.romania, Locale.Region.russia, Locale.Region.slovakia, Locale.Region.turkey]
        case .unitedArabEmirates: return [Locale.Region.iran, Locale.Region.oman, Locale.Region.qatar, Locale.Region.saudiArabia]
        case .unitedKingdom: return [Locale.Region.belgium, Locale.Region.denmark, Locale.Region.faroeIslands, Locale.Region.france, Locale.Region.germany, Locale.Region.guernsey, Locale.Region.ireland, Locale.Region.netherlands, Locale.Region.norway, Locale.Region.spain]
        case .unitedStates: return [Locale.Region.bahamas, Locale.Region.canada, Locale.Region.cuba, Locale.Region.mexico, Locale.Region.russia]
        case .uruguay: return [Locale.Region.argentina, Locale.Region.brazil]
        case .uzbekistan: return [Locale.Region.afghanistan, Locale.Region.kazakhstan, Locale.Region.kyrgyzstan, Locale.Region.tajikistan, Locale.Region.turkmenistan]

        case .vanuatu: return [Locale.Region.fiji, Locale.Region.solomonIslands]
        case .vaticanCity: return [Locale.Region.italy]
        case .venezuela: return [Locale.Region.aruba, Locale.Region.barbados, Locale.Region.brazil, Locale.Region.colombia, Locale.Region.dominica, Locale.Region.dominicanRepublic, Locale.Region.france, Locale.Region.grenada, Locale.Region.guyana, Locale.Region.montserrat, Locale.Region.netherlands, Locale.Region.puertoRico, Locale.Region.saintKittsNevis, Locale.Region.saintLucia, Locale.Region.saintVincentGrenadines, Locale.Region.trinidadTobago]
        case .vietnam: return [Locale.Region.brunei, Locale.Region.cambodia, Locale.Region.chinaMainland, Locale.Region.indonesia, Locale.Region.laos, Locale.Region.malaysia, Locale.Region.philippines, Locale.Region.taiwan, Locale.Region.thailand]

        case .wallisFutuna: return [Locale.Region.fiji, Locale.Region.samoa, Locale.Region.tonga, Locale.Region.tuvalu, Locale.Region.tokelau]
        case .westernSahara: return [Locale.Region.algeria, Locale.Region.mauritania, Locale.Region.morocco, Locale.Region.spain]

        case .yemen: return [Locale.Region.djibouti, Locale.Region.eritrea, Locale.Region.oman, Locale.Region.saudiArabia, Locale.Region.somalia]

        case .zambia: return [Locale.Region.angola, Locale.Region.botswana, Locale.Region.congoKinshasa, Locale.Region.malawi, Locale.Region.mozambique, Locale.Region.namibia, Locale.Region.tanzania, Locale.Region.zimbabwe]
        case .zimbabwe: return [Locale.Region.botswana, Locale.Region.mozambique, Locale.Region.southAfrica, Locale.Region.zambia]
        default: return nil
        }
    }
    
}
